######################################################################
##
## Filename: Counter_6_test.udo
## Created on: Thu Nov 24 19:42:12 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
